# Generated by Django 3.0 on 2019-12-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSCBatchTurnOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('DAY_SHIFT', 'Day Shift'), ('Night_SHIFT', 'Night Shift')], max_length=30, verbose_name='Shift')),
                ('current_Odate', models.DateTimeField(verbose_name='Current ODate')),
                ('verify_abends', models.BooleanField(default=False)),
                ('verify_no_abend', models.BooleanField(default=False)),
                ('wla_valid_notes', models.BooleanField(default=False)),
                ('bot_tickets', models.BooleanField(default=False)),
                ('all_abends_incident', models.BooleanField(default=False)),
                ('ucc_override', models.BooleanField(default=False)),
                ('service_req', models.BooleanField(default=False)),
                ('group_emails', models.BooleanField(default=False)),
                ('held_jobs', models.BooleanField(default=False)),
                ('fsc_report_reviewed', models.BooleanField(default=False)),
                ('notable_inc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notable Incidents')),
                ('qr_changes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='QR Changes')),
                ('bim', models.CharField(blank=True, max_length=1000, null=True, verbose_name='BIM')),
                ('other_shift_notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Other Shift Notes')),
            ],
        ),
    ]
